<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RootNamespace>Tec.Core.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Tec.Core\Tec.Core.csproj" />
    <ProjectReference Include="..\..\src\Tec.Driver.Abi\Tec.Driver.Abi.csproj" />
    <ProjectReference Include="..\..\src\Tec.Drivers.Simulator\Tec.Drivers.Simulator.csproj" />
    <ProjectReference Include="..\..\src\Tec.Drivers.Rd105\Tec.Drivers.Rd105.csproj" />
  </ItemGroup>

</Project>
